name: Run end-to-end tests

on:
  workflow_dispatch:

jobs:
  cypress-e2e:
    name: Run Cypress tests
    runs-on: ubuntu-latest
    container: cypress/browsers:latest

    steps:
      - uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        continue-on-error: true
        env:
          CYPRESS_baseUrl: https://trainee.tis.nhs.uk
          CYPRESS_password: ${{ secrets.E2E_TEST_PASS }}
          CYPRESS_username: ${{ secrets.E2E_TEST_USER }}
          CYPRESS_secret: ${{ secrets.E2E_TEST_SECRET }}
          CYPRESS_coverage: false
        with:
          browser: chrome

   